Create chemicals
sirclek/next-savoriq pull request #31
Opened 2024-10-24 13:54 UTC by wwdaas

2024-10-25 04:31 UTC, mattbeard03 requested changes
This does not merge with the current database but instead adds a new file and is incorrect. Please merge with current DB, as per ticket instructions

2024-10-26 01:55 UTC, mattbeard03 requested changes
Why did you put chemicals in that dont exist in the database?

2024-10-26 01:55 UTC, mattbeard03 commented on next-app/src/db/chemicals
> +            "name": "Maltol",
Not in the mock data.

2024-10-26 01:55 UTC, mattbeard03 commented on next-app/src/db/chemicals
> +            "name": "Cresols",
Not in the mock data.

2024-10-26 01:55 UTC, mattbeard03 commented on next-app/src/db/chemicals
> +            "name": "Hydroxymethylfurfural",
Not in the mock data.

2024-10-26 01:55 UTC, mattbeard03 commented on next-app/src/db/chemicals
> +            "name": "Lignin",
Not in the mock data.

2024-10-26 01:55 UTC, mattbeard03 commented on next-app/src/db/chemicals
> +            "name": "Tannins",
Not in the mock data.

2024-10-26 01:55 UTC, mattbeard03 commented on next-app/src/db/chemicals
> +            "name": "Glucose",
Not in the mock data.

2024-10-26 01:55 UTC, mattbeard03 commented on next-app/src/db/chemicals
> +            "name": "Fructose",
Not in the mock data.

2024-10-26 01:55 UTC, mattbeard03 commented on next-app/src/db/chemicals
> +            "name": "Sucrose",
Not in the mock data.

2024-10-26 01:55 UTC, mattbeard03 commented on next-app/src/db/chemicals
> +            "name": "Maltose",
Not in the mock data.

2024-10-26 01:55 UTC, mattbeard03 commented on next-app/src/db/chemicals
> +            "name": "Aspartame",
Not in the mock data.

2024-10-26 01:55 UTC, mattbeard03 commented on next-app/src/db/chemicals
> +            "name": "Sugar Alcohols",
Not in the mock data.

2024-10-26 01:55 UTC, mattbeard03 commented on next-app/src/db/chemicals
> +            "name": "Acetic Acid",
Not in the mock data.

2024-10-26 01:55 UTC, mattbeard03 commented on next-app/src/db/chemicals
> +            "name": "Cinnamaldehyde",
Not in the mock data.

2024-10-26 01:55 UTC, mattbeard03 commented on next-app/src/db/chemicals
> +            "name": "Capsaicin",
Not in the mock data.

2024-10-26 01:55 UTC, mattbeard03 commented on next-app/src/db/chemicals
> +            "name": "Piperine",
Not in the mock data.

2024-10-26 01:55 UTC, mattbeard03 commented on next-app/src/db/chemicals
> +            "name": "Hexyl Acetate",
Not in the mock data.

2024-10-26 01:55 UTC, mattbeard03 commented on next-app/src/db/chemicals
> +            "name": "Fatty Acids",
Not in the mock data.

2024-10-26 01:55 UTC, mattbeard03 commented on next-app/src/db/chemicals
> +            "name": "Essential Oils",
Not in the mock data.

2024-10-26 01:55 UTC, mattbeard03 commented on next-app/src/db/chemicals
> +            "name": "Fatty Acids and Esters",
Not in the mock data.

2024-10-26 01:55 UTC, mattbeard03 commented on next-app/src/db/chemicals
> +            "name": "Sugars",
Not in the mock data.

2024-10-26 01:55 UTC, mattbeard03 commented on next-app/src/db/chemicals
> +            "name": "Sugars and Carbohydrates",
Not in the mock data.

2024-10-26 13:15 UTC, wwdaas commented
[db.json](https://github.com/user-attachments/files/17530720/db.json)

2024-10-27 00:34 UTC, mattbeard03 commented
> [db.json](https://github.com/user-attachments/files/17530720/db.json)

You need to re-commit this merge request please.

2024-10-27 03:41 UTC, wwdaas commented
[db.json](https://github.com/user-attachments/files/17532674/db.json)

2024-10-27 10:03 UTC, mattbeard03 commented
@wwdaas please do the following:

Re-branch.

Open an editor on the new branch from current main.

Edit the JSON file located in the db folder.

Submit a new merge request.

2024-11-09 05:50 UTC, closed without merging