Flavour static page
sirclek/next-savoriq pull request #35
Opened 2024-10-28 07:39 UTC by MousaRaza7

![image](https://github.com/user-attachments/assets/e1e98710-b257-4b06-9409-5b028ee4d634)
I added the static flavour page in a seperate folder named flavours-static-draft for review. I have also added an transparent logo and the whiskeys images for the static flavour pages. I also added an vanillin chemical image which is a duplicate so don't worry about it.

2024-10-28 07:41 UTC, mattbeard03 requested changes

2024-10-28 07:41 UTC, mattbeard03 commented on next-app/public/images/chemicals/vanillin.png
Not required.

2024-10-28 07:41 UTC, mattbeard03 commented on next-app/public/images/logo/Logo.png
Not Required.

2024-10-30 00:09 UTC, MousaRaza7 commented on next-app/public/images/chemicals/vanillin.png
Removed

2024-10-30 00:10 UTC, MousaRaza7 commented on next-app/public/images/logo/Logo.png
Removed

2024-10-31 03:33 UTC, ngu892 commented
is it for individual flavours page?

2024-10-31 08:26 UTC, MousaRaza7 commented
> is it for individual flavours page?

yes

2024-11-16 02:50 UTC, closed without merging